Fix wp-restore to set table prefix.

diff --git a/bin/wp-restore b/bin/wp-restore
--- a/bin/wp-restore
+++ b/bin/wp-restore
@@ -62,6 +62,24 @@ fi
 if ! [[ -f $zipfile ]]; then
     echo "Warning: database file not found."
 else
+    # UpdraftPlus has header comments that contain useful information
+    header=$(zcat "$zipfile"|sed -ne '/^#/ p;/^$/ q')
+    echo "$header"
+    # Turn comments into underscore variables
+    eval $(echo "$header"|sed -ne '/: / { s/\(.*\): \(.*\)/\L\1="\2"/; s/^# //;s/ /_/g; p}')
+
+    if [ -n "$table_prefix" ]; then
+        echo "table prefix: $table_prefix"
+
+        # Modify the table prefix
+        if [ ! -f 'site/wp-config.php' ]; then
+            echo "Warning: can't find wp-config.php."
+        else
+            sudo sed -i'' -e "s/^\\\$table_prefix =.*\$/\\\$table_prefix = '${table_prefix}';/" site/wp-config.php \
+            || echo "Warning: can't update the WordPress table prefix!"
+        fi
+    fi
+
     zcat $zipfile \
         | sed -e '/^# -----/ a\' -e "/*\!40101 SET sql_mode='ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */;" \
         | wp db import -
